services:
  be:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./q4:/iiq/q4
    environment:
      - DB_URL=postgresql://postgres:password@db:5432/iiq
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: iiq
      PGPORT: 5432
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - iiq-db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iiq -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 2
volumes:
  iiq-db-data: